### ISSUE TITLE
no Docker Image for raspberry pi 5 available

### ISSUE THREAD

**Issue by chrys87** [home-assistant-libs/python-matter-server#1019]
Hello,

I try to install the docker image on an raspberry pi 5 but get an error using the following command (from the documentation):

[user@rpi~]$ sudo docker run -d   --name matter-server   --restart=unless-stopped   --security-opt apparmor=unconfined   -v $(pwd)/data:/data   --network=host   ghcr.io/home-assistant-libs/python-matter-server:stable
[sudo] password for user: 
Unable to find image 'ghcr.io/home-assistant-libs/python-matter-server:stable' locally
stable: Pulling from home-assistant-libs/python-matter-server
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

[user@rpi~]$ uname -a
Linux rpi 6.12.6-1-rpi #1 SMP Fri Dec 20 07:26:40 MST 2024 armv7l GNU/Linux

seems that the image is not available for raspi 5. could this be provided? this would be awsome.

**Comment by afharo** [comment]
Not a maintainer. But it looks like you installed the 32-bits version of the OS (`armv7`). This image is only published for the 64 bit version: https://github.com/home-assistant-libs/python-matter-server/pkgs/container/python-matter-server

My general recommendation is to install the 64-bits version of the OS in your Raspberry. It will make your life easier since many services are published for 64bits only due to missing 32bits libraries.
