### ISSUE TITLE
Error while trying to build the docker image (home-assistant-chip-core requirement)

### ISSUE THREAD

**Issue by acidicX** [home-assistant-libs/python-matter-server#182]
Hi,

I'm currently getting this error while trying to build the Dockerfile.dev:

```
#0 29.07   Installing build dependencies: started
#0 33.41   Installing build dependencies: finished with status 'done'
#0 33.42   Getting requirements to build wheel: started
#0 34.25   Getting requirements to build wheel: finished with status 'done'
#0 34.27   Installing backend dependencies: started
#0 35.95   Installing backend dependencies: finished with status 'done'
#0 35.96   Preparing metadata (pyproject.toml): started
#0 36.70   Preparing metadata (pyproject.toml): finished with status 'done'
#0 36.74 ERROR: Could not find a version that satisfies the requirement home-assistant-chip-core==2023.1.0; extra == "server" (from python-matter-server[server]) (from versions: none)
#0 36.75 ERROR: No matching distribution found for home-assistant-chip-core==2023.1.0; extra == "server"
------
failed to solve: executor failed running [/bin/bash -o pipefail -c pip3 install -U pip &&     pip3 install --no-cache-dir .[server]]: exit code: 1
```

I'm trying to build it on a pi4 so might be something arm specific?

**Comment by Drehwaehler** [comment]
It's not PI-specific. Got the same ERROR on my Intel64-Linux-Platform in a snap installation:
server:~ # pip install python-matter-server[server]
Collecting python-matter-server[server]
  Downloading python_matter_server-2.0.2-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 607 kB/s
Collecting dacite
  Downloading dacite-1.8.0-py3-none-any.whl (14 kB)
ERROR: Could not find a version that satisfies the requirement home-assistant-chip-clusters==2023.1.0 (from python-matter-server[server]) (from versions: none)
ERROR: No matching distribution found for home-assistant-chip-clusters==2023.1.0 (from python-matter-server[server])

**Comment by ArturoGuerra** [comment]
> Hi,
> 
> I'm currently getting this error while trying to build the Dockerfile.dev:
> 
> ```
> #0 29.07   Installing build dependencies: started
> #0 33.41   Installing build dependencies: finished with status 'done'
> #0 33.42   Getting requirements to build wheel: started
> #0 34.25   Getting requirements to build wheel: finished with status 'done'
> #0 34.27   Installing backend dependencies: started
> #0 35.95   Installing backend dependencies: finished with status 'done'
> #0 35.96   Preparing metadata (pyproject.toml): started
> #0 36.70   Preparing metadata (pyproject.toml): finished with status 'done'
> #0 36.74 ERROR: Could not find a version that satisfies the requirement home-assistant-chip-core==2023.1.0; extra == "server" (from python-matter-server[server]) (from versions: none)
> #0 36.75 ERROR: No matching distribution found for home-assistant-chip-core==2023.1.0; extra == "server"
> ------
> failed to solve: executor failed running [/bin/bash -o pipefail -c pip3 install -U pip &&     pip3 install --no-cache-dir .[server]]: exit code: 1
> ```
> 
> I'm trying to build it on a pi4 so might be something arm specific?

It does appear like arm64 is supported 
https://github.com/home-assistant-libs/chip-wheels/blob/0c000700ec4cef86090d24e539592dc72388385c/.github/workflows/build.yaml#L49-L54

**Comment by Slober3** [comment]
Hello,

I've got the same error....

ERROR: Could not find a version that satisfies the requirement home-assistant-chip-core==2023.1.0; extra == "server" (from python-matter-server[server]) (from versions: none)
ERROR: No matching distribution found for home-assistant-chip-core==2023.1.0; extra == "server"

**Comment by marcelveldt** [comment]
Are you able to install the wheels manually ?
https://pypi.org/project/home-assistant-chip-core/

If not, I'm afraid you will have to go into the hurdle of building the SDK yourself which is kind of... painful
Do note that we only publish wheels to pypi for Linux amd64 and arm64, so no 32 bits support.

**Comment by Drehwaehler** [comment]
I tried to install it manually, but this package is not found:

server:~ # pip3.9 -vvv install home-assistant-chip-core==2023.1.0
Using pip 20.2.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-9jx3dv6_
Created temporary directory: /tmp/pip-req-tracker-0exf4ofi
Initialized build tracking at /tmp/pip-req-tracker-0exf4ofi
Created build tracker: /tmp/pip-req-tracker-0exf4ofi
Entered build tracker: /tmp/pip-req-tracker-0exf4ofi
Created temporary directory: /tmp/pip-install-ul2t_ijs
1 location(s) to search for versions of home-assistant-chip-core:
* https://pypi.org/simple/home-assistant-chip-core/
Fetching project page and analyzing links: https://pypi.org/simple/home-assistant-chip-core/
Getting page https://pypi.org/simple/home-assistant-chip-core/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/home-assistant-chip-core/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/home-assistant-chip-core/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_aarch64: https://files.pythonhosted.org/packages/d0/f0/9b2355d632ae2835269509ef0cab0c0a3584b5de1d00cb51e9f06a4c5dd1/home_assistant_chip_core-2022.11.1-cp37-abi3-manylinux_2_31_aarch64.whl#sha256=03cabdc4f5469e62e36809af194560e6fd93cac9ab664e4ba87aed28e5903f4d (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_x86_64: https://files.pythonhosted.org/packages/f8/c9/f4f25b954f7a7997a41c082075bdb0f5ffb6b473f03f9106f81935b96135/home_assistant_chip_core-2022.11.1-cp37-abi3-manylinux_2_31_x86_64.whl#sha256=d566894afab183c3f59b9b7db290684fda89985007c9224641b067213b9b4a9c (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_aarch64: https://files.pythonhosted.org/packages/38/04/a5886ac7356d1202ec6586bf01e24201fefc52d10f54795229558b81f039/home_assistant_chip_core-2022.12.0-cp37-abi3-manylinux_2_31_aarch64.whl#sha256=a0daabbdbcd7797a4c1b7bfd44aea4a6938d1f89fbc4b55a2421055f1563da31 (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_x86_64: https://files.pythonhosted.org/packages/8b/3a/5c68a504407188c3b6b183fc2958b4fe5aafe17ebc0c442f1e3587c090c7/home_assistant_chip_core-2022.12.0-cp37-abi3-manylinux_2_31_x86_64.whl#sha256=4b99f53148a0f190d22e059e566bbee6a2d9e247c74140bda997157ccf2b3efc (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_aarch64: https://files.pythonhosted.org/packages/65/c7/38365638afbdc9360b599c3a9a5c12c219c2a9a253f3dc81d3527d0972b2/home_assistant_chip_core-2023.1.dev1801-cp37-abi3-manylinux_2_31_aarch64.whl#sha256=639b2990d9517cf0c172425c22bc366557242e89696b829401b5176271a59f3c (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_x86_64: https://files.pythonhosted.org/packages/4d/8a/40f143e49480baed9fb0711a2f1884ed3aa55a9fa0ef9a964ae3cf9b38cc/home_assistant_chip_core-2023.1.dev1801-cp37-abi3-manylinux_2_31_x86_64.whl#sha256=95ec795e466e7502a04e8530b6b852ced214ec38dad8ee92cba28669dacb50b6 (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_aarch64: https://files.pythonhosted.org/packages/3b/1f/506e402c33157f86366dc320870334d14a203a18f3e614868784fc0d3951/home_assistant_chip_core-2023.1.0-cp37-abi3-manylinux_2_31_aarch64.whl#sha256=84d686136b3fa051405425aee7421e79a15394e481c892402af0605f5883ad51 (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_x86_64: https://files.pythonhosted.org/packages/75/f8/8baa7b9f63f39d8e4cb15edec5e1370d7e5809b72786897f5eb76c5e3e77/home_assistant_chip_core-2023.1.0-cp37-abi3-manylinux_2_31_x86_64.whl#sha256=cd7c5b0c67f21545ee127687e1af11e0b5c7d207db30290a3c12491a9efbc473 (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_aarch64: https://files.pythonhosted.org/packages/e5/72/0910e9f88f65ce6eb0c608ea78bc2308ea5f26eac5c17fac81543cfb3387/home_assistant_chip_core-2023.2.0-cp37-abi3-manylinux_2_31_aarch64.whl#sha256=561126ad00da29387e3c4f93dab4b10d756c56a06ddd789d159b5e2ea774e3ce (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
  Skipping link: none of the wheel's tags match: cp37-abi3-manylinux_2_31_x86_64: https://files.pythonhosted.org/packages/ef/54/9c65f8910c2faa2c968fb1616c958c17975d797377a7896a9762e563df0f/home_assistant_chip_core-2023.2.0-cp37-abi3-manylinux_2_31_x86_64.whl#sha256=552963e2728f03f97fe9225db4127f8dc46147022f73a0ab74e9dba1d3a64593 (from https://pypi.org/simple/home-assistant-chip-core/) (requires-python:>=3.7)
Given no hashes to check 0 links for project 'home-assistant-chip-core': discarding no candidates
ERROR: Could not find a version that satisfies the requirement home-assistant-chip-core==2023.1.0 (from versions: none)
ERROR: No matching distribution found for home-assistant-chip-core==2023.1.0
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/usr/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 928, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for home-assistant-chip-core==2023.1.0
Removed build tracker: '/tmp/pip-req-tracker-0exf4ofi'

Is there any special location for this package home-assistant-chip-core? Also the new version is 2023.2.0. If i omit the ==2023.1.0 the same result.

**Comment by Slober3** [comment]
> Are you able to install the core wheel manually ? https://pypi.org/project/home-assistant-chip-core/
> 
> If not, I'm afraid you will have to go into the hurdle of building the SDK yourself which is kind of... painful Do note that we only publish wheels to pypi for Linux amd64 and arm64, so no 32 bits support.

Ahh yes that is it most likely  just checked my Pi 
Linux raspberrypi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/ Linux

And arm7l is 32 bit...

It's going to be a separate VM then 👍

**Comment by Drehwaehler** [comment]
If i download and install the Wheel directly, it failed also:
python3.9 -m pip -vvv install home_assistant_chip_core-2023.1.0-cp37-abi3-manylinux_2_31_x86_64.whl
Using pip 20.2.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-ve_rg90q
Created temporary directory: /tmp/pip-req-tracker-z47l9e3k
Initialized build tracking at /tmp/pip-req-tracker-z47l9e3k
Created build tracker: /tmp/pip-req-tracker-z47l9e3k
Entered build tracker: /tmp/pip-req-tracker-z47l9e3k
Created temporary directory: /tmp/pip-install-894qwfjw
ERROR: home_assistant_chip_core-2023.1.0-cp37-abi3-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 173, in resolve
    requirement_set.add_requirement(req)
  File "/usr/lib/python3.9/site-packages/pip/_internal/req/req_set.py", line 104, in add_requirement
    raise InstallationError(
pip._internal.exceptions.InstallationError: home_assistant_chip_core-2023.1.0-cp37-abi3-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
Removed build tracker: '/tmp/pip-req-tracker-z47l9e3k'

**Comment by Drehwaehler** [comment]
Finally the Solution:
Upgrading pip solved the problem.
python3.9 -m pip install --upgrade pip

**Comment by Drehwaehler** [comment]
During installation, i got this error:
  *** Error compiling '/usr/local/lib64/python3.9/site-packages/../../../lib/python3.9/site-packages/chip/configuration/__init__.py'...
  Sorry: IndentationError: unexpected indent (__init__.py, line 66)

**Comment by agners** [comment]
> It does appear like arm64 is supported https://github.com/home-assistant-libs/chip-wheels/blob/0c000700ec4cef86090d24e539592dc72388385c/.github/workflows/build.yaml#L49-L54

arm64 is supported (aarch64 is the same thing). arm32 is not, and won't be in the near future as compiling the Matter SDK for Linux 32-bit arm is not really supported upstream.

**Comment by ljmerza** [comment]
install raspbian 64bit (aarch64) and i still get `#0 91.97 ERROR: No matching distribution found for home-assistant-chip-core==2023.5.3; extra == "server"`

```
uname -m
aarch64
```

**Comment by agners** [comment]
The `Dockerfile.dev` seems to build fine when passing `--platform linux/arm64/v8` to the build command.

This issue was mainly about 32-bit build issue. Please open a new issue along with all information, such as:

- Exact commands you are running
- Docker version (e.g. output of `docker info`)
- OS version (e.g. `cat /etc/os-release`)
