### ISSUE TITLE
Possibility to provide official docker images

### ISSUE THREAD

**Issue by stackia** [home-assistant-libs/python-matter-server#268]
For homeassistant core users, sometimes it's not easy to setup dependencies required by matter-server (e.g. The pre-built CHIP wheels which are built in [Ubuntu 20.04](https://github.com/project-chip/connectedhomeip/blob/76eaffc1571cb240859a079693405627bf162c29/integrations/docker/images/chip-build/Dockerfile#L2) requires libssl1.1 but Ubuntu 22.04 no longer officially provides libssl1.1).

It'll be great if an official up-to-date docker image is provided in such cases.

**Comment by marcelveldt** [comment]
At this time we have no such plans because we focus on simplicity for now, which means the HAOS add-on but we do provide the dockerfile which you can build and you will not have to deal with the dependencies (just wait until the docker image is built).

We might revisit this once we're a bit further along the road btw but for now this is what it is.
