### ISSUE TITLE
Niko Friends of Hue switch detected as device but not as entity

### ISSUE THREAD

**Issue by hansmbakker** [home-assistant-libs/python-matter-server#318]
I am trying to run Philips Hue via the Matter integration on Home Assistant.

What works well:
- The Hue lights show up properly and I can switch them on/off
- The Hue motion sensor works properly (it shows the temperature and measured illumination)

However, a [Niko Friends of Hue switch](https://www.niko.eu/nl-nl/producten/draadloze-bedieningen/niko-dimschakelaar-voor-het-hue-systeem-productmodel-niko-0e16a165-034b-47ba-994b-6878c7514100) (EnOcean / Zigbee Green Power switch) is only detected as a device and not as an entity. I couldn't test it using HomeKit + Matter because I do not have an Apple Home Hub, but other people report that [on the Philips Hue side, (Friends of Hue) switches should be exposed](https://developers.meethue.com/forum/t/button-order-messed-up/6783/3).

It shows up like this:
![image](https://github.com/home-assistant-libs/python-matter-server/assets/3463496/4727168a-6da4-4501-a735-a6612712d570)

Is this because the platform type (button / switch?) is not supported in HA yet?

**Comment by marcelveldt** [comment]
Well, actually button devices are never exposed as entities in Home Assistant, that is a design choice. That is because a button/remote has no controls, it emits an event when something is pressed. In Home Assistant we expose these events to the automation engine.

For example for the regular Hue integration in Home Assistant you will have those events available.
As for Matter, unfortunately we are working on some bugs regarding device events. It works already but events are now delayed with a few minutes. This will hopefully be resolved very soon.

**Comment by marcelveldt** [comment]
Closing here as it is a non issue. Like I said this will be addressed in a future update where we will translate "devices that emit events" such as a remote or wall rocker into a sensible new entity representation in HA.
