### ISSUE TITLE
Possibility to add Bluetooth-Proxy instead of Hosts BT-Stack

### ISSUE THREAD

**Issue by spammads** [home-assistant-libs/python-matter-server#406]
I realized that commissioning uses the Hosts Bluetoothstack. In edge-environments or in combination with Homeassistant or/and running Esphome-Bluetooth-Proxy it would be great if the matter-server could be configured to use this external-bluetooth-device for commissioning. I know. Low priority. But I really would appreciate the effort. Nevertheless: Many thanks for the server.

**Comment by marcelveldt** [comment]
At this time we do not use the built-in commissioning because it requires a bluetooth adapter and even if that is present it will crash the bluetooth integration (or vice versa). Commissioning is doen using the HA Companion Apps (see the documentation) and it will use the bluetooth adapter of the phone doing the commissioning as well as handling the wifi/thread credentials.

At some point we will also open up the possibility to do the commissioning directly from the HA host but we need to work out both the UI for that in some config panel and fix the coexistence issues of Bluetooth. 

The idea of using the bluetooth proxies popped in our heads as well and that would offcourse be awesome but that will require a lot of work as currently the whole bluetooth provisioning is done by the sdk itself (and we just pass in an adapter). It is on the wish list but do not expect it to arrive anytime soon.
