### ISSUE TITLE
VLAN Support

### ISSUE THREAD

**Issue by artem-zinnatullin** [home-assistant-libs/python-matter-server#441]
Hi all,

Python-Matter-Server docs clearly state: 

>"Matter uses link-local multicast protocols which do not work across different LANs or VLANs".
> [Link](https://github.com/home-assistant-libs/python-matter-server/blob/7dbd689d271d4daca98d2d27c040830586dca295/README.md?plain=1#L47) 

And indeed I cannot connect to Matter devices across VLANs even though my firewall rules allow talking to the homelab server across VLANs and it works perfectly with Apple HomeKit devices that live on `NoT` VLAN:

```js
ERROR [281473144318416] Error handling message: CommandMessage(message_id='d169d714c8c542e5ad748a7f8584dfea', command='commission_with_code', args={'code': 'MT:C2E13K4527AVR60LN00'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 173, in commission_with_code
    raise NodeCommissionFailed(
matter_server.common.errors.NodeCommissionFailed: Commission with code failed for node 7
```

---

Now, Matter (correct me if I'm wrong) is considered a local-first smart home protocol, and that's what community is so hyped about it. Which means that Matter devices ***shouldn't need internet access*** to work with HomeAssistant and many users like me would want to put Matter devices on separate "NoT" VLAN to isolate them from other home networks and the Internet.

It has been long established in smart home community that multiple VLANs is the way to go to minimize data leaks, improve privacy and security:

- `Main` network
	- Isolated from Guest, NoT, IoT, Cameras
- `Guest` network
	- Isolated from Main, NoT, IoT, Cameras
- `NoT`:
	- Isolated from Internet, Main, Guest, IoT, Cameras
- `IoT`:
	- Isolated from Main, Guest, NoT, Cameras
- `Cameras`:
	- Isolated from Internet, Main, Guest, NoT, IoT

HomeAssistant server and Matter-Server however are allowed to talk to all of these networks except Guest to control smart home devices.

---

Now with all this in mind, how does one suppose to configure Matter devices so that they sit on a `NoT` network w/o access to Internet and other home networks while still being able to talk to Python-Matter-Server?

I suppose one way would be to deploy an instance of Python-Matter-Server directly in `NoT` network with `NoT` IP so it does not cross VLANs when talking to Matter devices sitting in `NoT`. But then I'm sure I'll have some bad Matter devices that will require internet and will sit on `IoT` network, am I supposed to deploy 2nd instance of Python-Matter-Server on `IoT` network as well or get multiple IPs for the Python-Matter-Server…? Am I supposed to buy more Raspberry Pi-ish boards just to run Python-Matter-Server in different VLANs…? 

I am really confused and am sure many others are too 🙃 

P.S. Thank you for your work!

**Comment by dankocrnkovic** [comment]
I Agree... This should really be resolved. If mDNS is working ok in vlans this should too.  Its early, my hopes are high...

**Comment by Jc2k** [comment]
Outsider here, I work on homekit protocol within HA. Wanted to offer what I know working with some of these protocols.

This is a protocol limitation, this project is just implementing those protocols. There is nothing this project can do.

In order to understand what is going on and why you need a good grasp of the OSI model, especially layer 2 vs layer 3 and above. You need to understand when a packet is switched and when it is routed. Even packets that physically go to your router might be switched rather than routed. You need to understand than vlans are a layer 2 thing, and at layer 2 there is actually no mechanism for packets to travel between vlans. Routing is what allows packets to travel between vlans. Routing is above layer 2 in the OSI model - it's part of IP. As such layer 2 protocols are "below" routing in the OSI model. No firewall is going to overcome that.

Matter (especially thread) is designed to work in spite of the host network as much as possible. This means devices self configure an overlay ipv6 within whatever layer 2 network you drop them. So if you had HA and a border router connected by just a switch, no router, no dns, no dhcp, no anything. It would still work. This uses standard ipv6 features that have existed for a long time. (Some of them a decade, some older). In general this means they work despite firewall rules - because typically firewall rules only apply on the router when traffic crosses a vlan boundary. Because matter/thread works within a vlan and traffic doesn't traverse your router, your firewall is irrelevant.

For Matter Thread devices, your border router uses icmp6 to announce a /64 ipv6 subnet to your Ethernet/wifi network, and to announce a route to the /64 of the thread mesh. These Icmp6 RAs don't cross VLAN boundaries. That's not a matter of firewall rules. The protocol is designed to work within a single layer 2 network. Those routes will never leave your VLAN.

If you run a custom kernel on your router you can circumvent that limitation. But routers strictly speaking aren't allowed to use dead neighbour detection. That's in black and white in a decade old RFC. Your firewall can't save you. So you'd be subject to 30 minute network outages every time the border router ip changed.
I'm talking about its link local address here. You can't pin that with your router.

Matter also uses mDNS. This is used to discover matter devices and to resolve their name into an ip address. By default this is also a protocol that does not work between vlans. It is not designed to. Some clever people found a way to fake it. So called repeaters. But because it wasn't designed to do this, this introduces problems. Sometimes old records build up in the repeater. Sometimes wrong addresses make it over the vlan boundary (and fe80 address is scoped to a vlan, so repeating over a vlan boundary is horrifically broken, but it happens). Vendors aren't fixing them even though they have been causing problems for years. And matter can't control them either.

Matter also uses ipv6 multicast to efficiently deal with multiple devices. Multicast is also not routable.

I have my HA on multiple vlans (by giving the container multiple macvlan interfaces) to avoid all this.

**Comment by marcelveldt** [comment]
If you want an over engineered network at your home that is totally fine but don't expect everything to work with that. These protocols are designed for regular residential network setups. 

if you insist on working with vLANS for your IoT devices, put HA (or any other Matter controller) on that IoT (v)LAN as well. issue resolved.

Its way easier than just open a single HTTP(s) port to HA than routing multicast traffic, isn't it ?

In any case do not use any mDNS forwarders/repeaters. Those things are pure evil. I have seen wireshark traces where the mDNS traffic was either malformed or just replicated like crazy. It only barely works with protocols like Airplay and Cast, imagine how it works with IPv6 traffic from Matter. On top of that it uses Neigbour Discovery like @Jc2k explained above.

Sorry guys to bring the bad news but these protocols are designed to operate on layer 2, not traverse all these enterprise grade networking stuff. For example the WiFi access points that just filter out some/all of the multicast traffic. In a (high density) business situation it makes perfectly sense to limit multicast traffic as much as possible because it may kill performance if there are many clients but in your home it will kill your devices.

I'm going to close this report as its a non issue. This is how its designed, just like all other consumer grade protocols like Airplay, Google Cast, Homekit etc. For those unfortunately exist the horrible workaround of a mDNS repeater. Let's just hope nobody is going to create workarounds for Matter, otherwise a lot of our time is going to be wasted on supporting this non-standard network setups, time that could otherwise have been spent on further developing Matter support in HA. 

**My golden tips for a perfectly fine working and safe setup:**
Flatten your network - save your enterprise networking syndrome for your work situation.
Buy devices you trust or not add them to your network at all. Worst case scenario create some firewall rules for them.
